// LEGEND: Onboarding form templates for all IFPE adapters
// Each template defines the fields required to onboard a legal customer
// All usage must comply with this LEGEND and the LICENSE

import { registerOnboardingTemplate } from "./registry";
import type { OnboardingTemplate } from "./schemas";

/* ── Stripe ───────────────────────────────────────────────── */
export const ONBOARDING_STRIPE: OnboardingTemplate = {
  id: "stripe",
  name: "Stripe",
  description: "Credit/debit card processing via Stripe. Supports global payments.",
  category: "payment",
  regions: ["global"],
  docsUrl: "https://docs.stripe.com/keys",
  fields: [
    {
      key: "secretKey",
      label: "Secret Key",
      type: "password",
      placeholder: "sk_live_...",
      description: "Your Stripe secret API key (starts with sk_live_ or sk_test_)",
      required: true,
      group: "credentials",
      envVar: "STRIPE_SECRET_KEY",
      order: 0,
    },
    {
      key: "webhookSecret",
      label: "Webhook Signing Secret",
      type: "password",
      placeholder: "whsec_...",
      description: "Used to verify incoming Stripe webhook events",
      required: true,
      group: "credentials",
      envVar: "STRIPE_WEBHOOK_SECRET",
      order: 1,
    },
  ],
  version: "2026-02-08",
};

/* ── Polar ────────────────────────────────────────────────── */
export const ONBOARDING_POLAR: OnboardingTemplate = {
  id: "polar",
  name: "Polar",
  description: "Subscriptions and digital products for open source via Polar.",
  category: "payment",
  regions: ["global"],
  docsUrl: "https://docs.polar.sh",
  fields: [
    {
      key: "apiKey",
      label: "API Key",
      type: "password",
      placeholder: "polar_...",
      description: "Your Polar API key",
      required: true,
      group: "credentials",
      envVar: "POLAR_API_KEY",
      order: 0,
    },
    {
      key: "webhookSecret",
      label: "Webhook Secret",
      type: "password",
      placeholder: "whsec_...",
      description: "Verify incoming Polar webhook events",
      required: true,
      group: "credentials",
      envVar: "POLAR_WEBHOOK_SECRET",
      order: 1,
    },
    {
      key: "baseUrl",
      label: "Base URL",
      type: "url",
      placeholder: "https://api.polar.sh",
      description: "Custom Polar API base URL (optional, defaults to production)",
      required: false,
      defaultValue: "https://api.polar.sh",
      group: "advanced",
      envVar: "POLAR_BASE_URL",
      order: 2,
    },
  ],
  version: "2026-02-08",
};

/* ── PayPal MX ────────────────────────────────────────────── */
export const ONBOARDING_PAYPAL_MX: OnboardingTemplate = {
  id: "paypal-mx",
  name: "PayPal México",
  description:
    "PayPal integration optimized for Mexico. Supports sandbox and live environments.",
  category: "payment",
  regions: ["MX"],
  docsUrl: "https://developer.paypal.com/docs/api/overview/",
  fields: [
    {
      key: "clientId",
      label: "Client ID",
      type: "text",
      placeholder: "AV3...",
      description: "PayPal REST API client ID",
      required: true,
      group: "credentials",
      envVar: "PAYPAL_MX_CLIENT_ID",
      order: 0,
    },
    {
      key: "clientSecret",
      label: "Client Secret",
      type: "password",
      placeholder: "EKj...",
      description: "PayPal REST API client secret",
      required: true,
      group: "credentials",
      envVar: "PAYPAL_MX_CLIENT_SECRET",
      order: 1,
    },
    {
      key: "webhookId",
      label: "Webhook ID",
      type: "text",
      placeholder: "WH-...",
      description: "PayPal webhook identifier for event verification",
      required: true,
      group: "credentials",
      envVar: "PAYPAL_MX_WEBHOOK_ID",
      order: 2,
    },
    {
      key: "environment",
      label: "Environment",
      type: "select",
      description: "PayPal API environment",
      required: true,
      defaultValue: "sandbox",
      options: [
        { label: "Sandbox", value: "sandbox" },
        { label: "Live", value: "live" },
      ],
      group: "configuration",
      envVar: "PAYPAL_MX_ENVIRONMENT",
      order: 3,
    },
  ],
  version: "2026-02-08",
};

/* ── MercadoPago ──────────────────────────────────────────── */
export const ONBOARDING_MERCADOPAGO: OnboardingTemplate = {
  id: "mercadopago",
  name: "MercadoPago",
  description:
    "MercadoPago integration for Latin America. Supports cards, OXXO, SPEI, and more.",
  category: "payment",
  regions: ["MX", "AR", "BR", "CO", "CL"],
  docsUrl: "https://www.mercadopago.com.mx/developers",
  fields: [
    {
      key: "accessToken",
      label: "Access Token",
      type: "password",
      placeholder: "APP_USR-...",
      description: "MercadoPago access token",
      required: true,
      group: "credentials",
      envVar: "MERCADOPAGO_ACCESS_TOKEN",
      order: 0,
    },
    {
      key: "webhookSecret",
      label: "Webhook Secret",
      type: "password",
      description: "Used to verify MercadoPago IPN/webhook notifications",
      required: true,
      group: "credentials",
      envVar: "MERCADOPAGO_WEBHOOK_SECRET",
      order: 1,
    },
    {
      key: "environment",
      label: "Environment",
      type: "select",
      description: "API environment",
      required: true,
      defaultValue: "sandbox",
      options: [
        { label: "Sandbox", value: "sandbox" },
        { label: "Production", value: "production" },
      ],
      group: "configuration",
      envVar: "MERCADOPAGO_ENVIRONMENT",
      order: 2,
    },
  ],
  version: "2026-02-08",
};

/* ── Compropago ───────────────────────────────────────────── */
export const ONBOARDING_COMPROPAGO: OnboardingTemplate = {
  id: "compropago",
  name: "ComproPago",
  description:
    "Cash payment networks in Mexico (OXXO, 7-Eleven, convenience stores).",
  category: "cash_payment",
  regions: ["MX"],
  docsUrl: "https://compropago.com/documentacion",
  fields: [
    {
      key: "apiKey",
      label: "API Key (Private)",
      type: "password",
      description: "ComproPago private API key",
      required: true,
      group: "credentials",
      envVar: "COMPROPAGO_API_KEY",
      order: 0,
    },
    {
      key: "publicKey",
      label: "Public Key",
      type: "text",
      description: "ComproPago public key for client-side integration",
      required: true,
      group: "credentials",
      envVar: "COMPROPAGO_PUBLIC_KEY",
      order: 1,
    },
    {
      key: "webhookSecret",
      label: "Webhook Secret",
      type: "password",
      description: "Verify event authenticity",
      required: true,
      group: "credentials",
      envVar: "COMPROPAGO_WEBHOOK_SECRET",
      order: 2,
    },
    {
      key: "environment",
      label: "Environment",
      type: "select",
      description: "API environment",
      required: true,
      defaultValue: "sandbox",
      options: [
        { label: "Sandbox", value: "sandbox" },
        { label: "Live", value: "live" },
      ],
      group: "configuration",
      envVar: "COMPROPAGO_ENVIRONMENT",
      order: 3,
    },
  ],
  version: "2026-02-08",
};

/* ── STP (Sistema de Transferencias y Pagos) ──────────────── */
export const ONBOARDING_STP: OnboardingTemplate = {
  id: "stp",
  name: "STP",
  description:
    "Mexican bank transfer network (SPEI). Direct interbank transfers for legal entities.",
  category: "bank_transfer",
  regions: ["MX"],
  docsUrl: "https://stpmex.com",
  fields: [
    {
      key: "empresa",
      label: "Empresa (Company Alias)",
      type: "text",
      placeholder: "MI_EMPRESA",
      description: "Your STP empresa/company alias as registered in STP",
      required: true,
      group: "credentials",
      envVar: "STP_EMPRESA",
      order: 0,
    },
    {
      key: "apiKey",
      label: "API Key / Signing Key",
      type: "password",
      description: "Private key or API key for signing STP requests",
      required: true,
      group: "credentials",
      envVar: "STP_API_KEY",
      order: 1,
    },
    {
      key: "clabe",
      label: "CLABE",
      type: "text",
      placeholder: "646180...",
      description: "18-digit CLABE account registered in STP",
      required: true,
      pattern: "^\\d{18}$",
      patternMessage: "CLABE must be exactly 18 digits",
      group: "credentials",
      envVar: "STP_CLABE",
      order: 2,
    },
    {
      key: "webhookSecret",
      label: "Webhook Secret",
      type: "password",
      description: "Verify STP webhook event signatures",
      required: true,
      group: "credentials",
      envVar: "STP_WEBHOOK_SECRET",
      order: 3,
    },
    {
      key: "environment",
      label: "Environment",
      type: "select",
      description: "STP API environment",
      required: true,
      defaultValue: "sandbox",
      options: [
        { label: "Sandbox", value: "sandbox" },
        { label: "Production", value: "production" },
      ],
      group: "configuration",
      envVar: "STP_ENVIRONMENT",
      order: 4,
    },
  ],
  version: "2026-02-08",
};

/* ── Thirdweb (Web3) ──────────────────────────────────────── */
export const ONBOARDING_THIRDWEB: OnboardingTemplate = {
  id: "thirdweb",
  name: "Thirdweb",
  description: "Web3 crypto payments via Thirdweb SDK. Multi-chain support.",
  category: "web3",
  regions: ["global"],
  docsUrl: "https://portal.thirdweb.com",
  fields: [
    {
      key: "secretKey",
      label: "Secret Key",
      type: "password",
      description: "Thirdweb API secret key",
      required: true,
      group: "credentials",
      envVar: "THIRDWEB_SECRET_KEY",
      order: 0,
    },
    {
      key: "webhookSecret",
      label: "Webhook Secret",
      type: "password",
      description: "Verify Thirdweb webhook events",
      required: true,
      group: "credentials",
      envVar: "THIRDWEB_WEBHOOK_SECRET",
      order: 1,
    },
    {
      key: "defaultChainId",
      label: "Default Chain ID",
      type: "text",
      placeholder: "1",
      description: "Default blockchain chain ID (e.g. 1 for Ethereum mainnet, 137 for Polygon)",
      required: true,
      defaultValue: "1",
      group: "configuration",
      envVar: "THIRDWEB_CHAIN_ID",
      order: 2,
    },
  ],
  version: "2026-02-08",
};

/* ── Shopify (Storefront) ─────────────────────────────────── */
export const ONBOARDING_SHOPIFY: OnboardingTemplate = {
  id: "shopify",
  name: "Shopify Storefront",
  description:
    "Shopify Storefront API integration for product syncing and cart management.",
  category: "storefront",
  regions: ["global"],
  docsUrl: "https://shopify.dev/docs/api/storefront",
  fields: [
    {
      key: "storeDomain",
      label: "Store Domain",
      type: "text",
      placeholder: "your-store.myshopify.com",
      description: "Your Shopify store domain",
      required: true,
      pattern: "^[a-z0-9-]+\\.myshopify\\.com$",
      patternMessage: "Must be a valid myshopify.com domain",
      group: "credentials",
      envVar: "SHOPIFY_STORE_DOMAIN",
      order: 0,
    },
    {
      key: "storefrontToken",
      label: "Storefront Access Token",
      type: "password",
      description: "Shopify Storefront API access token",
      required: true,
      group: "credentials",
      envVar: "SHOPIFY_STOREFRONT_TOKEN",
      order: 1,
    },
    {
      key: "apiVersion",
      label: "API Version",
      type: "text",
      placeholder: "2024-10",
      description: "Shopify API version (optional, defaults to latest stable)",
      required: false,
      defaultValue: "2024-10",
      group: "advanced",
      envVar: "SHOPIFY_API_VERSION",
      order: 2,
    },
  ],
  version: "2026-02-08",
};

/* ── Merchant Legal KYC ────────────────────────────────────── */
export const ONBOARDING_MERCHANT_LEGAL_KYC: OnboardingTemplate = {
  id: "merchant-legal-kyc",
  name: "Merchant Legal Profile (KYC/KYB)",
  description:
    "Legal entity registration for merchant onboarding. Collects business name, RFC/CURP, legal representative, and contact information required for KYC/KYB compliance in Mexico.",
  category: "compliance",
  regions: ["MX"],
  docsUrl: "https://www.sat.gob.mx/consulta/09554/verifica-si-estas-registrado-en-el-rfc",
  fields: [
    {
      key: "businessName",
      label: "Razón Social / Business Name",
      type: "text",
      placeholder: "Mi Empresa S.A. de C.V.",
      description: "Official legal business name as registered with SAT",
      required: true,
      group: "legal_entity",
      order: 0,
    },
    {
      key: "tradeName",
      label: "Nombre Comercial / Trade Name",
      type: "text",
      placeholder: "Mi Tienda",
      description: "Public-facing trade name (if different from legal name)",
      required: false,
      group: "legal_entity",
      order: 1,
    },
    {
      key: "entityType",
      label: "Tipo de Persona / Entity Type",
      type: "select",
      description: "Legal entity classification",
      required: true,
      options: [
        { label: "Persona Física", value: "persona_fisica" },
        { label: "Persona Física con Actividad Empresarial", value: "persona_fisica_empresarial" },
        { label: "Persona Moral (S.A. de C.V.)", value: "persona_moral_sa" },
        { label: "Persona Moral (S. de R.L.)", value: "persona_moral_srl" },
        { label: "Persona Moral (S.C.)", value: "persona_moral_sc" },
        { label: "Asociación Civil", value: "asociacion_civil" },
      ],
      group: "legal_entity",
      order: 2,
    },
    {
      key: "rfc",
      label: "RFC (Registro Federal de Contribuyentes)",
      type: "text",
      placeholder: "XAXX010101000",
      description: "Mexican tax identification number (12 chars for corporations, 13 for individuals)",
      required: true,
      pattern: "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$",
      patternMessage: "RFC must be 12-13 alphanumeric characters in the format: XXXX000000XX0",
      group: "tax_identity",
      order: 0,
    },
    {
      key: "curp",
      label: "CURP",
      type: "text",
      placeholder: "BADD110313HCMLNS09",
      description: "Clave Única de Registro de Población (required for Persona Física)",
      required: false,
      pattern: "^[A-Z]{4}\\d{6}[HM][A-Z]{5}[A-Z0-9]\\d$",
      patternMessage: "CURP must be 18 characters in the official format",
      group: "tax_identity",
      order: 1,
    },
    {
      key: "legalRepName",
      label: "Legal Representative Full Name",
      type: "text",
      placeholder: "Juan Pérez García",
      description: "Full name of the legal representative or account holder",
      required: true,
      group: "representative",
      order: 0,
    },
    {
      key: "legalRepEmail",
      label: "Legal Representative Email",
      type: "email",
      placeholder: "representante@empresa.mx",
      description: "Official contact email for legal representative",
      required: true,
      group: "representative",
      order: 1,
    },
    {
      key: "legalRepPhone",
      label: "Legal Representative Phone",
      type: "tel",
      placeholder: "+52 55 1234 5678",
      description: "Phone number with country code",
      required: true,
      pattern: "^\\+?\\d[\\d\\s-]{7,15}$",
      patternMessage: "Enter a valid phone number (e.g. +52 55 1234 5678)",
      group: "representative",
      order: 2,
    },
    {
      key: "businessAddress",
      label: "Domicilio Fiscal / Fiscal Address",
      type: "textarea",
      placeholder: "Calle, Número, Colonia, CP, Ciudad, Estado",
      description: "Registered fiscal address as it appears on Constancia de Situación Fiscal",
      required: true,
      group: "address",
      order: 0,
    },
    {
      key: "postalCode",
      label: "Código Postal",
      type: "text",
      placeholder: "06600",
      description: "5-digit Mexican postal code",
      required: true,
      pattern: "^\\d{5}$",
      patternMessage: "Postal code must be exactly 5 digits",
      group: "address",
      order: 1,
    },
    {
      key: "state",
      label: "Estado / State",
      type: "select",
      description: "Mexican state",
      required: true,
      options: [
        { label: "Aguascalientes", value: "AGS" },
        { label: "Baja California", value: "BC" },
        { label: "Baja California Sur", value: "BCS" },
        { label: "Campeche", value: "CAM" },
        { label: "Chiapas", value: "CHS" },
        { label: "Chihuahua", value: "CHI" },
        { label: "Ciudad de México", value: "CDMX" },
        { label: "Coahuila", value: "COA" },
        { label: "Colima", value: "COL" },
        { label: "Durango", value: "DGO" },
        { label: "Guanajuato", value: "GTO" },
        { label: "Guerrero", value: "GRO" },
        { label: "Hidalgo", value: "HGO" },
        { label: "Jalisco", value: "JAL" },
        { label: "Estado de México", value: "MEX" },
        { label: "Michoacán", value: "MIC" },
        { label: "Morelos", value: "MOR" },
        { label: "Nayarit", value: "NAY" },
        { label: "Nuevo León", value: "NL" },
        { label: "Oaxaca", value: "OAX" },
        { label: "Puebla", value: "PUE" },
        { label: "Querétaro", value: "QRO" },
        { label: "Quintana Roo", value: "QR" },
        { label: "San Luis Potosí", value: "SLP" },
        { label: "Sinaloa", value: "SIN" },
        { label: "Sonora", value: "SON" },
        { label: "Tabasco", value: "TAB" },
        { label: "Tamaulipas", value: "TAM" },
        { label: "Tlaxcala", value: "TLX" },
        { label: "Veracruz", value: "VER" },
        { label: "Yucatán", value: "YUC" },
        { label: "Zacatecas", value: "ZAC" },
      ],
      group: "address",
      order: 2,
    },
  ],
  version: "2026-02-08",
};

/* ── Merchant Bank Payout ─────────────────────────────────── */
export const ONBOARDING_MERCHANT_BANK_PAYOUT: OnboardingTemplate = {
  id: "merchant-bank-payout",
  name: "Merchant Bank Account (Payouts)",
  description:
    "Banking information for receiving payouts. Requires a CLABE interbank account, bank details, and beneficiary information compliant with Mexican banking regulations.",
  category: "compliance",
  regions: ["MX"],
  fields: [
    {
      key: "bankName",
      label: "Banco / Bank Name",
      type: "select",
      description: "Financial institution where the payout account is held",
      required: true,
      options: [
        { label: "BBVA", value: "BBVA" },
        { label: "Banorte", value: "BANORTE" },
        { label: "Santander", value: "SANTANDER" },
        { label: "HSBC", value: "HSBC" },
        { label: "Scotiabank", value: "SCOTIABANK" },
        { label: "Citibanamex", value: "CITIBANAMEX" },
        { label: "Banco Azteca", value: "BANCO_AZTECA" },
        { label: "Banregio", value: "BANREGIO" },
        { label: "Inbursa", value: "INBURSA" },
        { label: "BanCoppel", value: "BANCOPPEL" },
        { label: "STP", value: "STP" },
        { label: "Nu México", value: "NU_MEXICO" },
        { label: "Hey Banco", value: "HEY_BANCO" },
        { label: "Klar", value: "KLAR" },
      ],
      group: "bank_account",
      order: 0,
    },
    {
      key: "clabe",
      label: "CLABE Interbancaria",
      type: "text",
      placeholder: "646180110400000001",
      description: "18-digit interbank CLABE for SPEI transfers",
      required: true,
      pattern: "^\\d{18}$",
      patternMessage: "CLABE must be exactly 18 digits",
      group: "bank_account",
      order: 1,
    },
    {
      key: "beneficiaryName",
      label: "Nombre del Beneficiario",
      type: "text",
      placeholder: "Mi Empresa S.A. de C.V.",
      description: "Account holder name exactly as registered with the bank",
      required: true,
      group: "bank_account",
      order: 2,
    },
    {
      key: "beneficiaryRfc",
      label: "RFC del Beneficiario",
      type: "text",
      placeholder: "XAXX010101000",
      description: "Tax ID of the bank account holder (must match Legal Profile RFC)",
      required: true,
      pattern: "^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$",
      patternMessage: "RFC must be 12-13 alphanumeric characters",
      group: "bank_account",
      order: 3,
    },
    {
      key: "accountType",
      label: "Tipo de Cuenta / Account Type",
      type: "select",
      description: "Type of bank account",
      required: true,
      defaultValue: "checking",
      options: [
        { label: "Cuenta de Cheques (Checking)", value: "checking" },
        { label: "Cuenta de Ahorro (Savings)", value: "savings" },
        { label: "Cuenta Eje / Master Account", value: "master" },
      ],
      group: "bank_account",
      order: 4,
    },
    {
      key: "payoutCurrency",
      label: "Moneda de Pago / Payout Currency",
      type: "select",
      description: "Currency for payout disbursements",
      required: true,
      defaultValue: "MXN",
      options: [
        { label: "Peso Mexicano (MXN)", value: "MXN" },
        { label: "US Dollar (USD)", value: "USD" },
      ],
      group: "payout_config",
      order: 0,
    },
    {
      key: "payoutFrequency",
      label: "Frecuencia de Pago / Payout Frequency",
      type: "select",
      description: "How often payouts are disbursed",
      required: true,
      defaultValue: "weekly",
      options: [
        { label: "Diario (Daily)", value: "daily" },
        { label: "Semanal (Weekly)", value: "weekly" },
        { label: "Quincenal (Biweekly)", value: "biweekly" },
        { label: "Mensual (Monthly)", value: "monthly" },
      ],
      group: "payout_config",
      order: 1,
    },
    {
      key: "bankCertificateConsent",
      label: "I confirm this account is owned by the registered legal entity",
      type: "checkbox",
      description: "By checking, you certify that the bank account belongs to the legal entity registered in this onboarding process",
      required: true,
      group: "consent",
      order: 0,
    },
  ],
  version: "2026-02-08",
};

/* ── Merchant Tax / CFDI Configuration ────────────────────── */
export const ONBOARDING_MERCHANT_TAX_CFDI: OnboardingTemplate = {
  id: "merchant-tax-cfdi",
  name: "Merchant Tax & CFDI Configuration",
  description:
    "Tax regime and CFDI (Comprobante Fiscal Digital por Internet) configuration required for issuing invoices per SAT regulations in Mexico.",
  category: "compliance",
  regions: ["MX"],
  docsUrl: "https://www.sat.gob.mx/consultas/09702/consulta-tu-informacion-fiscal",
  fields: [
    {
      key: "taxRegime",
      label: "Régimen Fiscal",
      type: "select",
      description: "Tax regime as registered with the SAT",
      required: true,
      options: [
        { label: "601 - General de Ley Personas Morales", value: "601" },
        { label: "603 - Personas Morales con Fines no Lucrativos", value: "603" },
        { label: "605 - Sueldos y Salarios e Ingresos Asimilados", value: "605" },
        { label: "606 - Arrendamiento", value: "606" },
        { label: "607 - Régimen de Enajenación o Adquisición de Bienes", value: "607" },
        { label: "608 - Demás Ingresos", value: "608" },
        { label: "610 - Residentes en el Extranjero sin EP", value: "610" },
        { label: "611 - Ingresos por Dividendos", value: "611" },
        { label: "612 - Personas Físicas con Actividades Empresariales y Profesionales", value: "612" },
        { label: "614 - Ingresos por Intereses", value: "614" },
        { label: "616 - Sin Obligaciones Fiscales", value: "616" },
        { label: "620 - Sociedades Cooperativas de Producción", value: "620" },
        { label: "621 - Incorporación Fiscal", value: "621" },
        { label: "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras", value: "622" },
        { label: "623 - Opcional para Grupos de Sociedades", value: "623" },
        { label: "624 - Coordinados", value: "624" },
        { label: "625 - Régimen de las Actividades Empresariales con Ingresos a través de Plataformas Tecnológicas", value: "625" },
        { label: "626 - Régimen Simplificado de Confianza", value: "626" },
      ],
      group: "tax_regime",
      order: 0,
    },
    {
      key: "cfdiUse",
      label: "Uso de CFDI",
      type: "select",
      description: "Primary intended use of CFDI invoices for your business",
      required: true,
      defaultValue: "G03",
      options: [
        { label: "G01 - Adquisición de Mercancías", value: "G01" },
        { label: "G02 - Devoluciones, Descuentos o Bonificaciones", value: "G02" },
        { label: "G03 - Gastos en General", value: "G03" },
        { label: "I01 - Construcciones", value: "I01" },
        { label: "I02 - Mobiliario y Equipo de Oficina", value: "I02" },
        { label: "I03 - Equipo de Transporte", value: "I03" },
        { label: "I04 - Equipo de Computo y Accesorios", value: "I04" },
        { label: "I08 - Otra Maquinaria y Equipo", value: "I08" },
        { label: "P01 - Por Definir", value: "P01" },
        { label: "S01 - Sin Efectos Fiscales", value: "S01" },
        { label: "CP01 - Pagos", value: "CP01" },
      ],
      group: "tax_regime",
      order: 1,
    },
    {
      key: "ivaRate",
      label: "Tasa de IVA / VAT Rate",
      type: "select",
      description: "Default IVA rate applied to sales",
      required: true,
      defaultValue: "16",
      options: [
        { label: "16% (General)", value: "16" },
        { label: "8% (Zona Fronteriza)", value: "8" },
        { label: "0% (Tasa Cero)", value: "0" },
        { label: "Exento (Exempt)", value: "exempt" },
      ],
      group: "tax_rates",
      order: 0,
    },
    {
      key: "ivaWithheld",
      label: "Retención de IVA / IVA Withholding",
      type: "checkbox",
      description: "Enable if your business withholds IVA (e.g., platform economy)",
      required: false,
      group: "tax_rates",
      order: 1,
    },
    {
      key: "isrWithheld",
      label: "Retención de ISR / ISR Withholding",
      type: "checkbox",
      description: "Enable if your business withholds ISR (income tax)",
      required: false,
      group: "tax_rates",
      order: 2,
    },
    {
      key: "satCertSerial",
      label: "Número de Serie del Certificado SAT",
      type: "text",
      placeholder: "00001000000500000000",
      description: "Serial number of your CSD (Certificado de Sello Digital) issued by SAT",
      required: false,
      pattern: "^\\d{20}$",
      patternMessage: "Certificate serial must be exactly 20 digits",
      group: "certificates",
      order: 0,
    },
    {
      key: "satCsdPassword",
      label: "Contraseña del CSD",
      type: "password",
      description: "Password for the CSD certificate (Sello Digital)",
      required: false,
      group: "certificates",
      order: 1,
    },
    {
      key: "invoiceSeriesPrefix",
      label: "Serie de Factura / Invoice Series Prefix",
      type: "text",
      placeholder: "A",
      description: "Prefix for invoice numbering series (e.g., A, B, FA)",
      required: false,
      defaultValue: "A",
      group: "invoicing",
      order: 0,
    },
    {
      key: "invoiceNotes",
      label: "Notas de Factura / Default Invoice Notes",
      type: "textarea",
      placeholder: "Términos y condiciones de pago...",
      description: "Default notes or terms included in every invoice",
      required: false,
      group: "invoicing",
      order: 1,
    },
  ],
  version: "2026-02-08",
};

/* ── Merchant Document Upload ─────────────────────────────── */
export const ONBOARDING_MERCHANT_DOCUMENTS: OnboardingTemplate = {
  id: "merchant-documents",
  name: "Merchant Verification Documents",
  description:
    "Upload identification and verification documents required for KYC/KYB compliance: government ID (INE/IFE), proof of address, tax registration certificate, and articles of incorporation.",
  category: "compliance",
  regions: ["MX"],
  fields: [
    {
      key: "ineIdFront",
      label: "INE/IFE (Front)",
      type: "file",
      description: "Front side of the legal representative's INE/IFE voter ID. Accepted: PDF, JPG, PNG (max 10MB)",
      required: true,
      group: "identity_documents",
      order: 0,
    },
    {
      key: "ineIdBack",
      label: "INE/IFE (Back)",
      type: "file",
      description: "Back side of the INE/IFE voter ID. Accepted: PDF, JPG, PNG (max 10MB)",
      required: true,
      group: "identity_documents",
      order: 1,
    },
    {
      key: "proofOfAddress",
      label: "Comprobante de Domicilio / Proof of Address",
      type: "file",
      description: "Recent utility bill, bank statement, or government letter (max 3 months old). Accepted: PDF, JPG, PNG",
      required: true,
      group: "address_documents",
      order: 0,
    },
    {
      key: "constanciaSituacionFiscal",
      label: "Constancia de Situación Fiscal",
      type: "file",
      description: "Tax status certificate issued by SAT (Constancia de Situación Fiscal). Accepted: PDF",
      required: true,
      group: "tax_documents",
      order: 0,
    },
    {
      key: "actaConstitutiva",
      label: "Acta Constitutiva / Articles of Incorporation",
      type: "file",
      description: "Notarized articles of incorporation (required for Persona Moral). Accepted: PDF",
      required: false,
      group: "corporate_documents",
      order: 0,
    },
    {
      key: "poderNotarial",
      label: "Poder Notarial / Power of Attorney",
      type: "file",
      description: "Notarized power of attorney if signatory differs from legal representative. Accepted: PDF",
      required: false,
      group: "corporate_documents",
      order: 1,
    },
    {
      key: "csdCertificate",
      label: "Certificado de Sello Digital (CSD)",
      type: "file",
      description: "CSD certificate file (.cer) issued by SAT for digital invoicing",
      required: false,
      group: "tax_documents",
      order: 1,
    },
    {
      key: "csdPrivateKey",
      label: "Llave Privada del CSD (.key)",
      type: "file",
      description: "Private key file (.key) corresponding to the CSD certificate",
      required: false,
      group: "tax_documents",
      order: 2,
    },
    {
      key: "documentsConsent",
      label: "I authorize the processing of these documents for verification purposes",
      type: "checkbox",
      description: "By checking, you authorize the storage and processing of uploaded documents for KYC/KYB verification in accordance with Mexican data protection laws (LFPDPPP)",
      required: true,
      group: "consent",
      order: 0,
    },
  ],
  version: "2026-02-08",
};

/* ── Dispute Response ─────────────────────────────────────── */
export const ONBOARDING_DISPUTE_RESPONSE: OnboardingTemplate = {
  id: "dispute-response",
  name: "Dispute Response",
  description:
    "Submit evidence and respond to a payment dispute or chargeback. Merchants use this form to provide documentation supporting their case.",
  category: "dispute",
  regions: ["global"],
  fields: [
    {
      key: "disputeId",
      label: "Dispute / Chargeback ID",
      type: "text",
      placeholder: "dp_...",
      description: "The dispute or chargeback identifier from your payment processor",
      required: true,
      group: "dispute_details",
      order: 0,
    },
    {
      key: "orderId",
      label: "Order ID",
      type: "text",
      placeholder: "ord_...",
      description: "The original order associated with this dispute",
      required: true,
      group: "dispute_details",
      order: 1,
    },
    {
      key: "disputeType",
      label: "Dispute Type",
      type: "select",
      required: true,
      options: [
        { label: "Chargeback", value: "chargeback" },
        { label: "Pre-arbitration", value: "pre_arbitration" },
        { label: "Inquiry / Retrieval", value: "inquiry" },
        { label: "Fraud Claim", value: "fraud" },
        { label: "Product Not Received", value: "product_not_received" },
        { label: "Product Not as Described", value: "product_not_as_described" },
      ],
      group: "dispute_details",
      order: 2,
    },
    {
      key: "disputeAmount",
      label: "Disputed Amount",
      type: "text",
      placeholder: "150.00",
      description: "The amount being disputed (in original currency)",
      required: true,
      pattern: "^\\d+(\\.\\d{1,2})?$",
      patternMessage: "Must be a valid monetary amount (e.g. 150.00)",
      group: "dispute_details",
      order: 3,
    },
    {
      key: "disputeCurrency",
      label: "Currency",
      type: "select",
      required: true,
      defaultValue: "MXN",
      options: [
        { label: "MXN — Mexican Peso", value: "MXN" },
        { label: "USD — US Dollar", value: "USD" },
        { label: "EUR — Euro", value: "EUR" },
      ],
      group: "dispute_details",
      order: 4,
    },
    {
      key: "responseDescription",
      label: "Merchant Response",
      type: "textarea",
      placeholder: "Describe why this dispute should be resolved in your favor...",
      description: "Detailed explanation of your case, including timeline of events and any customer communication",
      required: true,
      group: "response",
      order: 0,
    },
    {
      key: "customerContactEvidence",
      label: "Customer Communication Log",
      type: "textarea",
      placeholder: "Paste or summarize email/chat exchanges with the customer...",
      description: "Evidence of communication with the customer regarding this transaction",
      required: false,
      group: "response",
      order: 1,
    },
    {
      key: "trackingNumber",
      label: "Shipping Tracking Number",
      type: "text",
      placeholder: "1Z999AA10123456784",
      description: "Carrier tracking number proving delivery (if applicable)",
      required: false,
      group: "evidence",
      order: 0,
    },
    {
      key: "deliveryConfirmation",
      label: "Delivery Confirmation / Proof of Delivery",
      type: "file",
      description: "Screenshot or document showing successful delivery. Accepted: PDF, JPG, PNG (max 10MB)",
      required: false,
      group: "evidence",
      order: 1,
    },
    {
      key: "invoiceReceipt",
      label: "Invoice / Receipt",
      type: "file",
      description: "The original invoice or receipt for the disputed transaction. Accepted: PDF, JPG, PNG",
      required: true,
      group: "evidence",
      order: 2,
    },
    {
      key: "additionalEvidence",
      label: "Additional Evidence",
      type: "file",
      description: "Any other supporting documents (contracts, signed agreements, usage logs). Accepted: PDF, JPG, PNG (max 10MB)",
      required: false,
      group: "evidence",
      order: 3,
    },
    {
      key: "merchantEmail",
      label: "Merchant Contact Email",
      type: "email",
      placeholder: "disputes@mybusiness.com",
      description: "Email for dispute resolution communications",
      required: true,
      group: "contact",
      order: 0,
    },
    {
      key: "disputeConsent",
      label: "I certify the information and evidence provided are accurate and complete",
      type: "checkbox",
      description: "By checking, you certify that all evidence submitted is authentic and you authorize processing for dispute resolution",
      required: true,
      group: "consent",
      order: 0,
    },
  ],
  version: "2026-02-08",
};

/* ── Refund Request ───────────────────────────────────────── */
export const ONBOARDING_REFUND_REQUEST: OnboardingTemplate = {
  id: "refund-request",
  name: "Refund Request",
  description:
    "Initiate a partial or full refund for an order. Available for merchants, operations teams, and customers (with order reference).",
  category: "refund",
  regions: ["global"],
  fields: [
    {
      key: "orderId",
      label: "Order ID",
      type: "text",
      placeholder: "ord_...",
      description: "The order to be refunded",
      required: true,
      group: "refund_details",
      order: 0,
    },
    {
      key: "transactionId",
      label: "Transaction / Payment ID",
      type: "text",
      placeholder: "pi_...",
      description: "The payment transaction identifier (from the payment processor)",
      required: false,
      group: "refund_details",
      order: 1,
    },
    {
      key: "refundType",
      label: "Refund Type",
      type: "select",
      required: true,
      options: [
        { label: "Full Refund", value: "full" },
        { label: "Partial Refund", value: "partial" },
      ],
      group: "refund_details",
      order: 2,
    },
    {
      key: "refundAmount",
      label: "Refund Amount",
      type: "text",
      placeholder: "75.00",
      description: "Amount to refund (required for partial refunds, auto-filled for full refunds)",
      required: false,
      pattern: "^\\d+(\\.\\d{1,2})?$",
      patternMessage: "Must be a valid monetary amount (e.g. 75.00)",
      group: "refund_details",
      order: 3,
    },
    {
      key: "refundCurrency",
      label: "Currency",
      type: "select",
      required: true,
      defaultValue: "MXN",
      options: [
        { label: "MXN — Mexican Peso", value: "MXN" },
        { label: "USD — US Dollar", value: "USD" },
        { label: "EUR — Euro", value: "EUR" },
      ],
      group: "refund_details",
      order: 4,
    },
    {
      key: "refundReason",
      label: "Reason for Refund",
      type: "select",
      required: true,
      options: [
        { label: "Customer requested cancellation", value: "customer_cancellation" },
        { label: "Product not received", value: "product_not_received" },
        { label: "Product damaged or defective", value: "product_damaged" },
        { label: "Product not as described", value: "product_not_as_described" },
        { label: "Duplicate charge", value: "duplicate_charge" },
        { label: "Fraudulent transaction", value: "fraud" },
        { label: "Service not provided", value: "service_not_provided" },
      ],
      group: "reason",
      order: 0,
    },
    {
      key: "refundDescription",
      label: "Additional Details",
      type: "textarea",
      placeholder: "Provide any additional context for this refund...",
      description: "Explain the circumstances or any additional relevant information",
      required: false,
      group: "reason",
      order: 1,
    },
    {
      key: "refundEvidence",
      label: "Supporting Evidence",
      type: "file",
      description: "Photos of damaged product, communication screenshots, or other documentation. Accepted: PDF, JPG, PNG (max 10MB)",
      required: false,
      group: "evidence",
      order: 0,
    },
    {
      key: "requesterName",
      label: "Requester Name",
      type: "text",
      placeholder: "Jane Doe",
      description: "Name of the person requesting the refund",
      required: true,
      group: "requester",
      order: 0,
    },
    {
      key: "requesterEmail",
      label: "Requester Email",
      type: "email",
      placeholder: "customer@example.com",
      description: "Email for refund status notifications",
      required: true,
      group: "requester",
      order: 1,
    },
    {
      key: "requesterRole",
      label: "Requester Role",
      type: "select",
      required: true,
      options: [
        { label: "Customer", value: "customer" },
        { label: "Merchant", value: "merchant" },
        { label: "Operations / Support", value: "ops" },
      ],
      group: "requester",
      order: 2,
    },
    {
      key: "refundConsent",
      label: "I confirm this refund request is legitimate and authorized",
      type: "checkbox",
      description: "By checking, you confirm that this refund is authorized and the information provided is accurate",
      required: true,
      group: "consent",
      order: 0,
    },
  ],
  version: "2026-02-08",
};

/* ── Dispute Merchant Operations ──────────────────────────── */
export const ONBOARDING_DISPUTE_MERCHANT_OPS: OnboardingTemplate = {
  id: "dispute-merchant-ops",
  name: "Dispute Resolution & Case Tracking",
  description:
    "Internal merchant/operations form for tracking and resolving disputes and refund cases. Manages case lifecycle from open to resolution.",
  category: "dispute",
  regions: ["global"],
  fields: [
    {
      key: "caseId",
      label: "Case ID",
      type: "text",
      placeholder: "CASE-2026-...",
      description: "Internal case tracking identifier",
      required: true,
      group: "case_tracking",
      order: 0,
    },
    {
      key: "relatedDisputeId",
      label: "Related Dispute / Refund ID",
      type: "text",
      placeholder: "dp_... or ref_...",
      description: "Link to the original dispute or refund request ID",
      required: false,
      group: "case_tracking",
      order: 1,
    },
    {
      key: "caseType",
      label: "Case Type",
      type: "select",
      required: true,
      options: [
        { label: "Dispute / Chargeback", value: "dispute" },
        { label: "Refund", value: "refund" },
        { label: "Fraud Investigation", value: "fraud_investigation" },
        { label: "Compliance Review", value: "compliance_review" },
      ],
      group: "case_tracking",
      order: 2,
    },
    {
      key: "caseStatus",
      label: "Case Status",
      type: "select",
      required: true,
      defaultValue: "open",
      options: [
        { label: "Open", value: "open" },
        { label: "Under Investigation", value: "investigating" },
        { label: "Evidence Submitted", value: "evidence_submitted" },
        { label: "Awaiting Customer Response", value: "awaiting_customer" },
        { label: "Escalated", value: "escalated" },
        { label: "Resolved — Won", value: "resolved_won" },
        { label: "Resolved — Lost", value: "resolved_lost" },
        { label: "Resolved — Refunded", value: "resolved_refunded" },
        { label: "Closed", value: "closed" },
      ],
      group: "case_tracking",
      order: 3,
    },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      required: true,
      defaultValue: "medium",
      options: [
        { label: "Low", value: "low" },
        { label: "Medium", value: "medium" },
        { label: "High", value: "high" },
        { label: "Critical", value: "critical" },
      ],
      group: "case_tracking",
      order: 4,
    },
    {
      key: "assignedTo",
      label: "Assigned To",
      type: "email",
      placeholder: "agent@mybusiness.com",
      description: "Email of the team member handling this case",
      required: true,
      group: "assignment",
      order: 0,
    },
    {
      key: "escalationContact",
      label: "Escalation Contact",
      type: "email",
      placeholder: "manager@mybusiness.com",
      description: "Contact for case escalation (if needed)",
      required: false,
      group: "assignment",
      order: 1,
    },
    {
      key: "internalNotes",
      label: "Internal Notes",
      type: "textarea",
      placeholder: "Add investigation notes, timeline updates, actions taken...",
      description: "Internal-only notes for the operations team (not shared with customer)",
      required: false,
      group: "resolution",
      order: 0,
    },
    {
      key: "resolutionSummary",
      label: "Resolution Summary",
      type: "textarea",
      placeholder: "Summarize the resolution outcome...",
      description: "Final resolution summary (required when closing a case)",
      required: false,
      group: "resolution",
      order: 1,
    },
    {
      key: "resolutionEvidence",
      label: "Resolution Evidence / Documentation",
      type: "file",
      description: "Final documentation supporting the resolution. Accepted: PDF, JPG, PNG (max 10MB)",
      required: false,
      group: "resolution",
      order: 2,
    },
    {
      key: "financialImpact",
      label: "Financial Impact",
      type: "text",
      placeholder: "150.00",
      description: "Total financial impact of this case (amount lost, refunded, or recovered)",
      required: false,
      pattern: "^\\d+(\\.\\d{1,2})?$",
      patternMessage: "Must be a valid monetary amount",
      group: "resolution",
      order: 3,
    },
    {
      key: "opsConsent",
      label: "I confirm this case update is accurate and authorized",
      type: "checkbox",
      description: "By checking, you confirm the information is accurate and you are authorized to update this case",
      required: true,
      group: "consent",
      order: 0,
    },
  ],
  version: "2026-02-08",
};

/* ── All Templates ────────────────────────────────────────── */
export const ALL_ONBOARDING_TEMPLATES: OnboardingTemplate[] = [
  ONBOARDING_STRIPE,
  ONBOARDING_POLAR,
  ONBOARDING_PAYPAL_MX,
  ONBOARDING_MERCADOPAGO,
  ONBOARDING_COMPROPAGO,
  ONBOARDING_STP,
  ONBOARDING_THIRDWEB,
  ONBOARDING_SHOPIFY,
  ONBOARDING_MERCHANT_LEGAL_KYC,
  ONBOARDING_MERCHANT_BANK_PAYOUT,
  ONBOARDING_MERCHANT_TAX_CFDI,
  ONBOARDING_MERCHANT_DOCUMENTS,
  ONBOARDING_DISPUTE_RESPONSE,
  ONBOARDING_REFUND_REQUEST,
  ONBOARDING_DISPUTE_MERCHANT_OPS,
];

/* ── Auto-Register ────────────────────────────────────────── */
for (const template of ALL_ONBOARDING_TEMPLATES) {
  registerOnboardingTemplate({ template });
}
